### PR TITLE
Solid v1 update

### PR DESCRIPTION
**Pull request by trusktr**
- update solid to 1.0
- update lume/cli to fix Webpack build/test breakage due to Node 17

### CODE REVIEW

**Comment by trusktr** [comment]
Now that tests are running, they're totally failing. `npm test` should work now locally after the lume/cli update, with or without Node 17.

**Comment by mosheduminer** [comment]
Maybe try reverting the undefined check? Let's see if the update alone is causing problems.

**Comment by mosheduminer** [comment]
Looks like the tests were successful. 👍

**Comment by trusktr** [comment]
Cool. I suppose we'd have to update tests to have that new option, but no biggie since we'll replace it all anyway

**Comment by trusktr** [comment]
Now we need to update lume/element to V1 too

**Pull request merged**
